### ISSUE TITLE
Windows 10 Support in the OS Filters

### ISSUE THREAD

**Issue by PJTewkesbury** [dblock/dotnetinstaller#90] opened 2015-07-20 14:15 UTC
Hi,

Does any one know when there will be  a new release of DotNetInstaller which supports windows 10 i the os filters?

Thanks

Peter Tewkesbury

**Comment by dblock** [comment] 2015-07-20 15:02
@icnocop Want to cut a release?

**Comment by GunzBlazing** [comment] 2015-07-31 17:34
I second the release. We have Windows 10 machines in our sphere and dotnetinstaller says it's running on Windows 8 on them. Not a big deal. The installation still works fine but for customers with Windows 10 it could be unsettling.

**Comment by GunzBlazing** [comment] 2015-07-31 17:36
I'd rather if DNI said nothing on the bottom label if it doesn't recognize the operating system.

**Comment by dblock** [comment] 2015-07-31 19:29
FYI there was some debate before about displaying "unsupported platform" or something like that. I think this was a deliberate choice, but I am not sure.

**Comment by GunzBlazing** [comment] 2015-07-31 20:12
I can't see how taking the latest OS(Windows 8) is a good option. I don't think it should ever say anything down there. What's the point? The user doesn't need to be reminded what OS they are running on. They have a million ways to check that already. It seems like more of a debugging thing to verify DNI is detecting the OS correctly. Those kinds of things are usually removed for release. It's equivalent to a sanity check debug print statement IMO.

**Comment by dblock** [comment] 2015-07-31 20:17
I agree, I am pretty sure it's a bug anyway. Unsupported versions come out as `osMax` or something like that in https://github.com/dblock/dotnetinstaller/blob/master/dotNetInstallerToolsLib/OsUtil.cpp#L31 and shouldn't be displayed as any known release.

**Comment by dblock** [comment] 2015-07-31 20:18
@GunzBlazing You should open that as a bug, and try to fix it? I am not sure if the problem is in os detection code or just display.

**Comment by GunzBlazing** [comment] 2015-07-31 20:52
Does that mean I have to build the code?

**Comment by dblock** [comment] 2015-07-31 21:10
If you want it fixed for sure, yes. I think @icnocop hasn't been very active lately and I haven't used DNI in like 8 years. I am happy to help though, but I am not going to do the research and the fix for this.

**Comment by p4bl0cs** [comment] 2015-09-01 13:45
OK, not being able to hide the OS info label is pretty lame and not recognizing Windows 10 is even worse. The only workaround I've found was to change the label's position to a negative one (i.e. -1000, -1000) or set the width and height to 1 (thankfully no pixel whatsoever is shown).
Hope it helps and hope someone can take care of this bug.

**Comment by dblock** [comment] 2015-09-01 19:32
Cmon someone contribute! I'll help fix/merge.

**Comment by icnocop** [comment] 2015-09-06 18:10
Should we cut a new release now or should we wait until dotNetInstaller has the ability to hide the operating system label all together?

Thank you.

**Comment by dblock** [comment] 2015-09-07 20:02
I would cut a release.

**Comment by icnocop** [comment] 2015-09-09 06:20
[2.4 was just released.](https://github.com/dblock/dotnetinstaller/releases/tag/2.4)

**Comment by icnocop** [comment] 2015-09-09 06:31
The 2.4 release supports using the operating system filter "win10" for Windows 10.

**Closed by icnocop** 2015-09-09 06:31 UTC
Labels: chore

**Comment by icnocop** [comment] 2015-09-09 06:37
I added a new issue here: [Add the ability to optionally hide the operating system label in the UI](https://github.com/dblock/dotnetinstaller/issues/91)
